services:
  app:
    build: .
    ports:
      - "3006:3000"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./public:/app/public
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
